- name: install server puppet
  package:
   name: puppetserver
   update_cache: yes
  when: ansible_hostname == "devops"

- name: instalando o puppet-agent
  package:
   name: puppet-agent
   update_cache: yes
