- name: exercicios
  hosts: all
  tasks: 
   - name: criando usuarios
     user: 
      name: "{{item}}"
      shell: /bin/bash
     with_items:
      - developer
      - suporte
      - luis
   - name: instalando pacotes
     package:
      name: "{{ item.pacote }}"
     when: ansible_os_family == item.distro
     with_items:
       - {pacote: git, distro: Debian }
       - {pacote: figlet, distro: Debian}
       - {pacote: vim, distro: Debian}
       - {pacote: git, distro: RedHat}
       - {pacote: epel-release, distro: RedHat}
       - {pacote: vim, distro: RedHat}
   - name: Criando o diretorio
     file:
      path: "{{item.arquivo}}"
      state: "{{item.tipo}}"
     with_items:
      - {arquivo: /tmp/devops, tipo: directory}

   - name: colocando conteudo no arquivo
## Modulo para popular um arquivo ##     
     blockinfile:
## Parametro para criar um arquivo caso ele nao exista ##
      create: yes
      path: /tmp/devops/file
      block: |
       sou devops
       na 4linux
       fala tu
