- name: Criando um loop
  hosts: all
  tasks:
   - name: garantindo o epel-release
     yum:
      name: epel-release
## Usando variaveis do Factor ##
     when: ansible_os_family == "RedHat"


   - name: instalando pacotes
     package:
      name: "{{ item }}"
### Faz um loop dentro do codigo abaixo os nomes dos pacotes a serem instalados ###
     with_items:
      - vim
      - cowsay
      - figlet
