- name: criando condicoes
  hosts: all
  tasks:
  - name: instalando pacotes para debian
    package:
     name: "{{item}}"
    when: ansible_os_family == "Debian"
    with_items:
     - vim
     - htop
     - cowsay
     - figlet
     - git

  - name: instalando pacotes para centos
    yum:
     name: "{{item}}"
    when: ansible_os_family == "RedHat"
    with_items:
     - epel-release
     - git
     - figlet 
  - name: adicionando usuarios padroes
    user:
## Criar variaveis para usuarios
     name: "{{item.nome}}"
     shell: "{{item.base}}"
## Usando a variavel criada
    with_items:
      - {nome: luis, base: "/bin/bash" }
      - {nome: jorge, base: "/bin/bash" }
      - {nome: joana, base: "/bin/bash" }
